/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Field */

#ifndef _Included_Field
#define _Included_Field
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Field
 * Method:    equals
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_reflect_Field_equals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    get
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_reflect_Field_get
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getBoolean
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_reflect_Field_getBoolean
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getByte
 * Signature: (Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_java_lang_reflect_Field_getByte
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getChar
 * Signature: (Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_java_lang_reflect_Field_getChar
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getDeclaringClass
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_reflect_Field_getDeclaringClass
  (JNIEnv *, jobject);

/*
 * Class:     Field
 * Method:    getDouble
 * Signature: (Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_reflect_Field_getDouble
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getFloat
 * Signature: (Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_java_lang_reflect_Field_getFloat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getInt
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_java_lang_reflect_Field_getInt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getLong
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_java_lang_reflect_Field_getLong
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getModifiers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_lang_reflect_Field_getModifiers
  (JNIEnv *, jobject);

/*
 * Class:     Field
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_lang_reflect_Field_getName
  (JNIEnv *, jobject);

/*
 * Class:     Field
 * Method:    getShort
 * Signature: (Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_java_lang_reflect_Field_getShort
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Field
 * Method:    getType
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_reflect_Field_getType
  (JNIEnv *, jobject);

/*
 * Class:     Field
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_lang_reflect_Field_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     Field
 * Method:    set
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_set
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     Field
 * Method:    setBoolean
 * Signature: (Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setBoolean
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     Field
 * Method:    setByte
 * Signature: (Ljava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setByte
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     Field
 * Method:    setChar
 * Signature: (Ljava/lang/Object;C)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setChar
  (JNIEnv *, jobject, jobject, jchar);

/*
 * Class:     Field
 * Method:    setDouble
 * Signature: (Ljava/lang/Object;D)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setDouble
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     Field
 * Method:    setFloat
 * Signature: (Ljava/lang/Object;F)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setFloat
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     Field
 * Method:    setInt
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setInt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     Field
 * Method:    setLong
 * Signature: (Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setLong
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     Field
 * Method:    setShort
 * Signature: (Ljava/lang/Object;S)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_setShort
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     Field
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_lang_reflect_Field_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
