/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class VMObject */

#ifndef _Included_VMObject
#define _Included_VMObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VMObject
 * Method:    clone
 * Signature: (Ljava/lang/Cloneable;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_VMObject_clone
  (JNIEnv *, jclass, jobject);

/*
 * Class:     VMObject
 * Method:    notify
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_lang_VMObject_notify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     VMObject
 * Method:    notifyAll
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_lang_VMObject_notifyAll
  (JNIEnv *, jclass, jobject);

/*
 * Class:     VMObject
 * Method:    wait
 * Signature: (Ljava/lang/Object;JI)V
 */
JNIEXPORT void JNICALL Java_java_lang_VMObject_wait
  (JNIEnv *, jclass, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
